@startuml AuthenticationServiceSequence

actor Пользователь as User
participant "Основное приложение" as App
participant "Сервис аутентификации" as Auth
participant "SQL база данных" as SQLDB

User -> App : Отправка логина и пароля
App -> Auth : Передача данных для аутентификации
Auth -> SQLDB : Проверка учетных данных
SQLDB --> Auth : Возвращение результата проверки

alt Успешная аутентификация
    Auth -> Auth : Генерация JWT-токена
    Auth -> App : Возвращение JWT-токена
    App -> User : Успешная аутентификация
else Ошибка аутентификации
    Auth -> App : Сообщение об ошибке
    App -> User : Ошибка аутентификации
end

@enduml
